[package]
name = "imgal_java"
version = "0.1.0"
authors = ["Edward Evans"]
edition = "2024"

[lib]
name = "imgal_java"
crate-type = ["cdylib"]
doc = false

[dependencies]
imgal_c = { path = "../imgal_c" }
ndarray = "0.16.0"
